### ISSUE TITLE
Workflow completes successfully, but site URL returns a 404

### ISSUE THREAD

**Issue by ianbayne** [andrewmcodes/bridgetown-gh-pages-action#4]
# Bug Report

## Describe the bug

Hi there! Thanks for the GH actions script! I'm trying to make use of it to deploy my Bridgetown site to GH Pages, but even though the workflow completes successfully, when I navigate to my site's URL, the server is returning a 404.

# Reproduction Steps

1. Create a new Bridgetown site.
2. Create a deploy workflow with content that's the same as either the Basic, Manual, or Advanced usages (edited of course as necessary) on https://github.com/andrewmcodes/bridgetown-gh-pages-action.
3. Commit and push.
4. Wait for GH Action to finish.
5. Navigate to site's URL.
6. See 404 page.

# Expected behavior

Site should build and deploy, and the server should return it successfully.

## Stacktrace

<img width="871" alt="Screen Shot 2021-04-17 at 13 03 03" src="https://user-images.githubusercontent.com/10363087/115101248-68a05b00-9f7d-11eb-9090-02184b300969.png">
<img width="874" alt="Screen Shot 2021-04-17 at 13 03 16" src="https://user-images.githubusercontent.com/10363087/115101258-6e963c00-9f7d-11eb-96fe-0f3794c2cb35.png">
<img width="881" alt="Screen Shot 2021-04-17 at 13 03 29" src="https://user-images.githubusercontent.com/10363087/115101262-748c1d00-9f7d-11eb-8677-fe0ef1df8ff6.png">

<img width="864" alt="Screen Shot 2021-04-17 at 13 03 42" src="https://user-images.githubusercontent.com/10363087/115101265-78b83a80-9f7d-11eb-8fdd-4f19bac54ab4.png">

## Action Version & Workflow File

- Version v0.0.3

### Workflow File

Last one tried:
```yaml
name: Deploy

on:
  push:
    branches: [master]

jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy to GitHub Pages
        uses: andrewmcodes/bridgetown-gh-pages-action@v0.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          github_actor: ${{ github.actor }}
          default_branch: master # default_branch is not an expected input according to the GH actions log but is listed at https://github.com/andrewmcodes/bridgetown-gh-pages-action#inputs
          site_location: './'
          build_location: './output'
          deploy_branch: 'gh-pages'
          commit_message: 'new: release site'
```
